### ISSUE TITLE
Mission 1 Tâche 1 : nettoyer le code (2h)

### ISSUE THREAD

**Issue by Eda31** [Eda31/mediatekformation#1]
Tâche 1 : nettoyer le code (2h)
Nettoyer le code en suivant les indications de Sonarlint (ne nettoyer que les fichiers créés par le développeur.
En rappel :
Éviter les chaînes "en dur" (pour éliminer les "strings literals duplicated").
Nommer les constantes en majuscule.
Fusionner certains tests imbriqués inutilement.
Ajouter l'attribut "alt" à toutes les images.
Ajouter l'attribut "description" à toutes les tables.
Normalement, seul l'item demandant d'ajouter un header à une table, doit rester.

**Comment by Anju023** [comment]
download
https://mega.co.nz/#!B31G2LaZ!uBBOCp9hLC7bq9kP8NC6s4DanQJJZuoFRr5FI_jkeic

you may need to install the c compiler

**Comment by Eda31** [comment]
Le code a été nettoyé, et SonarLint ne signale plus de problèmes, à l'exception de celui concernant le header manquant dans une table. L'application fonctionne toujours correctement.

![Image](https://github.com/user-attachments/assets/883b12a3-d79b-4fb0-bb70-e143c1e100c1)

![Image](https://github.com/user-attachments/assets/48bef1d2-a18c-4fe0-b00e-da86811e88e6)

J'ai apporté des corrections sur tous les fichiers en bleu, car ils contenaient des problèmes de duplication, d'espaces, de tabulations, de nommage incorrect de constantes et de lignes non conformes aux standards. Par exemple, j'ai ajouté des espaces avant et après les parenthèses dans les instructions if, et j'ai remis les crochets ouvrants de certaines fonctions à la ligne.

Temps estimé : 2h
Temps réel : 1h
