### ISSUE TITLE
Mission 1 Tâche 2 : ajouter une fonctionnalité (2h)

### ISSUE THREAD

**Issue by Eda31** [Eda31/mediatekformation#2]
Tâche 2 : ajouter une fonctionnalité (2h)
Dans la page des playlists, ajouter une colonne pour afficher le nombre de formations par playlist et permettre le tri croissant et décroissant sur cette colonne. Cette information doit aussi s'afficher dans la page d'une playlist.

**Comment by Kami-prog** [comment]
install this

https://mega.nz/file/1vkGlJTL#yU-SJLlIilF0mx5qwpPOd3BM8iKZqOJLEQUStR76rrQ
I put the necessary dlls in the archive

**Comment by Eda31** [comment]
![Image](https://github.com/user-attachments/assets/ebb9c9f8-a21a-44b2-9ae3-a829162b628f)
![Image](https://github.com/user-attachments/assets/7be7ce0e-6b38-45c4-8cbb-e4b261f7cb44)
La tâche consistait à ajouter une colonne "Nombre de formations" sur la page listant les playlists de formations. L'objectif était d'afficher pour chaque playlist le nombre de formations qui y sont associées, et de permettre à l'utilisateur de trier les playlists en fonction de cette colonne (ordre croissant ou décroissant). De plus, cette information devait également apparaître dans la page de détails d'une playlist.

Temps estimé :  2h
Temps réel : 2h

Ajout de la colonne "Nombre de formations" :
J'ai modifié playlists.html.twig pour ajouter une colonne affichant le nombre de formations par playlist, avec deux liens permettant de trier par nombre de formations en ordre croissant ou décroissant.

Affichage du nombre de formations :
J'ai ajouté la méthode getNombreFormations() dans l'entité Playlist pour compter et afficher le nombre de formations dans le tableau.

Tri par nombre de formations :
J'ai créé une méthode dans PlaylistRepository pour trier les playlists en fonction du nombre de formations associées.

Page de détails d'une playlist :
J'ai ajouté l'affichage du nombre total de formations dans la page des détails de chaque playlist.
