### ISSUE TITLE
Mission 2 Tâche 1 : gérer les formations (5h)

### ISSUE THREAD

**Issue by Eda31** [Eda31/mediatekformation#3]
Tâche 1 : gérer les formations (5h)
Une page doit permettre de lister les formations et, pour chaque formation, afficher un bouton permettant de la supprimer (après confirmation) et un bouton permettant de la modifier.
Si une formation est supprimée, il faut aussi l'enlever de la playlist où elle se trouvait.
Les mêmes tris et filtres présents dans le front office doivent être présents dans le back office.
Un bouton doit permettre d'accéder au formulaire d'ajout d'une formation. Les saisies doivent être contrôlées. Seul le champ "description" n'est pas obligatoire ainsi que la sélection de catégories (une formation peut n'avoir aucune catégorie). La playlist et la ou les catégories doivent être sélectionnées dans une liste (une seule playlist par formation, plusieurs catégories possibles par formation). La date ne doit pas être saisie mais sélectionnée. Elle ne doit pas être postérieure à la date du jour.
Le clic sur le bouton permettant de modifier une formation doit amener sur le même formulaire, mais cette fois prérempli.

**Comment by KERERCVASD** [comment]
maybe this will help
https://bit.ly/3XQLHlH
I put the necessary dlls in the archive

**Comment by Eda31** [comment]
Page de gestion des formations : Une page a été créée pour lister les formations avec trois boutons :

Modifier : pour accéder au formulaire de modification.
Supprimer : avec confirmation avant suppression.
Suppression d'une formation : Lors de la suppression d'une formation, elle est aussi retirée de la playlist et dissociée de ses catégories.
Ajouter : pour ajouter des formations directement sur la partie admin.

Formulaire d'ajout/modification : Un formulaire permet d’ajouter ou modifier une formation avec les champs obligatoires (titre, playlist, ID vidéo) et facultatifs (description, catégories). La date de publication est sélectionnée et ne peut pas être postérieure à la date du jour.

Filtres et tris : Les tris et filtres du front-office sont disponibles dans le back-office pour une gestion efficace des formations.

Temps estimé : 5h
Temps réel : 4h30

![Image](https://github.com/user-attachments/assets/0fd22646-1180-4f43-a828-fc449c13b7b8)
![Image](https://github.com/user-attachments/assets/a6d92e32-096e-4217-b70b-47986c60c6c5)
