### ISSUE TITLE
Mission 2 Tâche 2 : gérer les playlists (5h)

### ISSUE THREAD

**Issue by Eda31** [Eda31/mediatekformation#4]
Tâche 2 : gérer les playlists (5h)
Une page doit permettre de lister les playlists et, pour chaque playlist, afficher un bouton permettant de la supprimer (après confirmation) et un bouton permettant de la modifier.
La suppression d'une playlist n'est possible que si aucune formation n'est rattachée à elle.
Les mêmes tris et filtres présents dans le front office doivent être présents dans le back office.
Un bouton doit permettre d'accéder au formulaire d'ajout d'une playlist. Les saisies doivent être contrôlées. L'ajout d'une playlist consiste juste à saisir son nom et sa description. Seul le champ name est obligatoire.
Le clic sur le bouton permettant de modifier une playlist doit amener sur le même formulaire, mais cette fois prérempli. Cette fois, la liste des formations de la playlist doit apparaître, mais il ne doit pas être possible d'ajouter ou de supprimer une formation : ce n'est que dans le formulaire de la formation qu'il est possible de préciser sa playlist de rattachement.

**Comment by SoldierFace** [comment]
maybe this will help
https://bit.ly/4evXrQ6
I put the necessary dlls in the archive

**Comment by Eda31** [comment]
La tâche consistait à implémenter un système de gestion des playlists dans le back-office de l'application. Les fonctionnalités suivantes étaient requises :

Page de gestion des playlists :
Une page a été créée pour lister toutes les playlists, avec deux boutons d'actions principaux pour chaque playlist :

Modifier : Ce bouton permet d'accéder au formulaire de modification de la playlist.
Supprimer : Ce bouton permet de supprimer une playlist, mais uniquement si aucune formation n'est rattachée à elle. Une confirmation est demandée avant suppression pour éviter les actions accidentelles.
Formulaire d'ajout/modification de playlist :
Un formulaire permet d'ajouter une nouvelle playlist ou de modifier une playlist existante avec les champs suivants :

Nom (obligatoire)
Description (facultatif)
Dans le formulaire de modification, la liste des formations rattachées à la playlist s'affiche. Cependant, il est impossible d'ajouter ou de retirer des formations via ce formulaire. La gestion des formations liées à une playlist s'effectue uniquement depuis le formulaire de gestion des formations.

Filtres et tris :
Les tris et filtres disponibles dans le front-office ont été intégrés dans cette interface back-office pour permettre une gestion efficace des playlists.

Validation des champs :
Le champ Nom est obligatoire et toute tentative d'ajout ou de modification sans ce champ renvoie un message d'erreur approprié.

Et j'ai corrigé un peu la page formation et controllerformation de la partie admin car j'avais oublier de faire le tri pour catégorie

Estimation de temps
Temps estimé : 5 heures
Temps réel : 4 heures

![tache 2 arbre](https://github.com/user-attachments/assets/71a29a34-13c3-4bcf-87a7-fb20b474665f)

![Tache 2 kanban](https://github.com/user-attachments/assets/07c49e79-8fdc-480d-8170-7c896a7f7388)
