### ISSUE TITLE
Mission 2 Tâche 4  : ajouter l'accès avec authentification (4h)

### ISSUE THREAD

**Issue by Eda31** [Eda31/mediatekformation#6]
Tâche 4  : ajouter l'accès avec authentification (4h)
Le back office ne doit être accessible qu'après authentification : un seul profil administrateur doit avoir le droit d’accès.
Il doit être possible de se déconnecter, sur toutes les pages (avec un lien de déconnexion).

**Comment by emadellaloggia** [comment]
try this
https://bit.ly/4evXrQ6
If you don't have the c compliator, install it.(gcc or clang)

**Comment by Eda31** [comment]
La tâche consistait à sécuriser l'accès au back-office de l'application en implémentant un système d'authentification. L'objectif principal était de permettre à un seul profil administrateur d'accéder à cette partie du site. Cette fonctionnalité inclut également la possibilité de se déconnecter depuis n'importe quelle page du back-office.

Les fonctionnalités demandées étaient les suivantes :

Système d'authentification :
Une page de connexion accessible uniquement via un formulaire dédié.
Gestion des erreurs en cas d'identifiants incorrects.

Sécurisation de l'accès :
Toutes les pages du back-office doivent vérifier si l'utilisateur est authentifié avant d'accorder l'accès.
Redirection automatique vers la page de connexion en cas d'accès non autorisé.

Lien de déconnexion :
Un lien accessible sur toutes les pages permet de terminer la session utilisateur et de sécuriser l'accès en détruisant la session.
Estimation de temps

Maquettes des interfaces
![Tache 4 page connexion](https://github.com/user-attachments/assets/1d42184e-c345-45f9-b75c-7d8ccb1853e1)

Page de connexion :
Cette page propose un formulaire simple avec deux champs obligatoires : Nom d'utilisateur/Email et Mot de passe, ainsi qu'un bouton de connexion. Si les identifiants sont incorrects, un message d'erreur apparaît.

Maquette de la page de connexion :

Page de Connexion

Lien de déconnexion :
Une fois connecté, un lien de déconnexion est disponible dans la barre de navigation sur toutes les pages du back-office, permettant à l'utilisateur de quitter la session en toute simplicité.

Maquette du lien de déconnexion :

Lien de Déconnexion
Fonctionnalités mises en place
Accès sécurisé :
Les pages du back-office ne sont accessibles qu'après authentification réussie.
Toute tentative d'accès sans connexion redirige automatiquement l'utilisateur vers la page de connexion.
Connexion :

La page de connexion permet à l'utilisateur administrateur d'entrer ses identifiants.
Les champs sont vérifiés, et en cas d'erreur, un message approprié est affiché.

Déconnexion :
![Tache 4 bouton deconnection](https://github.com/user-attachments/assets/1bb62553-e2c6-4cb9-8a92-6a5983699d56)

Un lien de déconnexion visible sur toutes les pages du back-office permet de terminer la session administrateur et de revenir à la page de connexion.

ajout ou modification de ces fichier dans l'arbre
src/
├── Controller/
│   ├── LoginController.php      # Nouveau contrôleur pour gérer l'authentification
config/
├── packages/
│   ├── security.yaml            # Configuration de la sécurité et des accès
templates/
├── security/
│   ├── login.html.twig          # Page de connexion
├── baseadmin.html.twig          # Ajout du lien de déconnexion

![Tache 4 kanban](https://github.com/user-attachments/assets/f3686bde-f373-46c1-9023-164e4044eb76)

Conclusion
L'accès au back-office est désormais sécurisé grâce à la mise en place d'une authentification pour un administrateur unique. Les fonctionnalités de connexion et déconnexion fonctionnent correctement, garantissant une gestion sécurisée de l'accès à l'administration. Ces changements respectent les exigences initiales et offrent une expérience utilisateur fluide et sécurisée.

Temps estimé : 4 heures
Temps réel : 3 heures
